import { Injectable } from '@nestjs/common';

/**
 * ControllerGeneratorService
 * 
 * Generates Spring Boot REST controller classes with CRUD endpoints.
 * Includes validation, error handling, and proper HTTP status codes.
 */
@Injectable()
export class ControllerGeneratorService {
  /**
   * Generate a Spring Boot REST controller
   */
  generateController(
    resourceName: string,
    dtoClassName: string,
    packageName: string
  ): string {
    const controllerName = `${resourceName}Controller`;
    const resourcePath = resourceName.toLowerCase();
    const dtoVarName = dtoClassName.charAt(0).toLowerCase() + dtoClassName.slice(1);

    return `package ${packageName}.controller;

import ${packageName}.dto.${dtoClassName}Dto;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * REST Controller for ${resourceName}
 * 
 * Provides CRUD endpoints with automatic validation
 * Generated by FormSync Runtime Binding Validator
 */
@RestController
@RequestMapping("/api/${resourcePath}")
@CrossOrigin(origins = "*")
public class ${controllerName} {

    // In-memory storage for demonstration
    private final Map<Long, ${dtoClassName}Dto> storage = new ConcurrentHashMap<>();
    private final AtomicLong idGenerator = new AtomicLong(1);

    /**
     * Create a new ${resourceName}
     * 
     * @param ${dtoVarName} the ${resourceName} data (validated)
     * @return created ${resourceName} with generated ID
     */
    @PostMapping
    public ResponseEntity<Map<String, Object>> create(@Valid @RequestBody ${dtoClassName}Dto ${dtoVarName}) {
        Long id = idGenerator.getAndIncrement();
        storage.put(id, ${dtoVarName});
        
        Map<String, Object> response = new HashMap<>();
        response.put("id", id);
        response.put("data", ${dtoVarName});
        response.put("message", "${resourceName} created successfully");
        
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    /**
     * Get all ${resourceName}s
     * 
     * @return list of all ${resourceName}s
     */
    @GetMapping
    public ResponseEntity<Map<String, Object>> getAll() {
        Map<String, Object> response = new HashMap<>();
        response.put("data", new ArrayList<>(storage.values()));
        response.put("count", storage.size());
        
        return ResponseEntity.ok(response);
    }

    /**
     * Get a ${resourceName} by ID
     * 
     * @param id the ${resourceName} ID
     * @return the ${resourceName} data
     */
    @GetMapping("/{id}")
    public ResponseEntity<Map<String, Object>> getById(@PathVariable Long id) {
        ${dtoClassName}Dto ${dtoVarName} = storage.get(id);
        
        if (${dtoVarName} == null) {
            Map<String, Object> errorResponse = new HashMap<>();
            errorResponse.put("error", "${resourceName} not found");
            errorResponse.put("id", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(errorResponse);
        }
        
        Map<String, Object> response = new HashMap<>();
        response.put("id", id);
        response.put("data", ${dtoVarName});
        
        return ResponseEntity.ok(response);
    }

    /**
     * Update a ${resourceName}
     * 
     * @param id the ${resourceName} ID
     * @param ${dtoVarName} the updated ${resourceName} data (validated)
     * @return updated ${resourceName}
     */
    @PutMapping("/{id}")
    public ResponseEntity<Map<String, Object>> update(
            @PathVariable Long id,
            @Valid @RequestBody ${dtoClassName}Dto ${dtoVarName}) {
        
        if (!storage.containsKey(id)) {
            Map<String, Object> errorResponse = new HashMap<>();
            errorResponse.put("error", "${resourceName} not found");
            errorResponse.put("id", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(errorResponse);
        }
        
        storage.put(id, ${dtoVarName});
        
        Map<String, Object> response = new HashMap<>();
        response.put("id", id);
        response.put("data", ${dtoVarName});
        response.put("message", "${resourceName} updated successfully");
        
        return ResponseEntity.ok(response);
    }

    /**
     * Delete a ${resourceName}
     * 
     * @param id the ${resourceName} ID
     * @return success message
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Map<String, Object>> delete(@PathVariable Long id) {
        ${dtoClassName}Dto removed = storage.remove(id);
        
        if (removed == null) {
            Map<String, Object> errorResponse = new HashMap<>();
            errorResponse.put("error", "${resourceName} not found");
            errorResponse.put("id", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(errorResponse);
        }
        
        Map<String, Object> response = new HashMap<>();
        response.put("message", "${resourceName} deleted successfully");
        response.put("id", id);
        
        return ResponseEntity.ok(response);
    }

    /**
     * Exception handler for validation errors
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public Map<String, Object> handleValidationExceptions(MethodArgumentNotValidException ex) {
        Map<String, String> errors = new HashMap<>();
        ex.getBindingResult().getAllErrors().forEach((error) -> {
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();
            errors.put(fieldName, errorMessage);
        });
        
        Map<String, Object> response = new HashMap<>();
        response.put("error", "Validation failed");
        response.put("validationErrors", errors);
        
        return response;
    }
}
`;
  }
}
