import { Injectable } from '@nestjs/common';

/**
 * SpringBootScaffoldService
 * 
 * Generates the core Spring Boot project files:
 * - Main application class
 * - application.properties
 * - pom.xml (Maven build file)
 * - README.md with instructions
 */
@Injectable()
export class SpringBootScaffoldService {
  /**
   * Generate main Spring Boot application class
   */
  generateMainClass(packageName: string, className: string): string {
    const packagePath = packageName;
    
    return `package ${packagePath};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main Spring Boot Application
 * Generated by FormSync Runtime Binding Validator
 */
@SpringBootApplication
public class ${className}Application {

    public static void main(String[] args) {
        SpringApplication.run(${className}Application.class, args);
    }
}
`;
  }

  /**
   * Generate application.properties file
   */
  generateApplicationProperties(appName: string): string {
    return `# Spring Boot Application Configuration
# Generated by FormSync Runtime Binding Validator

spring.application.name=${appName.toLowerCase().replace(/\s+/g, '-')}
server.port=8080

# Enable validation
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JSON configuration
spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
`;
  }

  /**
   * Generate Maven pom.xml
   */
  generatePomXml(groupId: string, artifactId: string, projectName: string): string {
    return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/>
    </parent>
    
    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>${projectName}</name>
    <description>Generated Spring Boot project from FormSync schema</description>
    
    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <dependencies>
        <!-- Spring Boot Web Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <!-- Spring Boot Validation -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        
        <!-- Lombok for reducing boilerplate -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        
        <!-- Spring Boot Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`;
  }

  /**
   * Generate README.md with instructions
   */
  generateReadme(projectName: string, resourceName: string): string {
    return `# ${projectName}

This is a Spring Boot REST API project generated by FormSync Runtime Binding Validator.

## Prerequisites

- Java 17 or higher
- Maven 3.6 or higher

## Running the Application

\`\`\`bash
# Build and run the application
mvn spring-boot:run
\`\`\`

The server will start on http://localhost:8080

## API Endpoints

The following REST endpoints are available for \`${resourceName}\`:

### Create ${resourceName}
\`\`\`
POST /api/${resourceName.toLowerCase()}
Content-Type: application/json

{
  // Your ${resourceName} data here
}
\`\`\`

### Get All ${resourceName}
\`\`\`
GET /api/${resourceName.toLowerCase()}
\`\`\`

### Get ${resourceName} by ID
\`\`\`
GET /api/${resourceName.toLowerCase()}/{id}
\`\`\`

### Update ${resourceName}
\`\`\`
PUT /api/${resourceName.toLowerCase()}/{id}
Content-Type: application/json

{
  // Updated ${resourceName} data
}
\`\`\`

### Delete ${resourceName}
\`\`\`
DELETE /api/${resourceName.toLowerCase()}/{id}
\`\`\`

## Validation

All request bodies are automatically validated based on the schema constraints.
Invalid requests will return a 400 Bad Request with detailed validation errors.

## Testing

You can test the API using curl, Postman, or any HTTP client:

\`\`\`bash
# Example: Create a new resource
curl -X POST http://localhost:8080/api/${resourceName.toLowerCase()} \\
  -H "Content-Type: application/json" \\
  -d '{ ... }'
\`\`\`

## Project Structure

\`\`\`
src/
├── main/
│   ├── java/
│   │   └── [package]/
│   │       ├── Application.java       # Main application class
│   │       ├── controller/            # REST controllers
│   │       └── dto/                   # Data Transfer Objects
│   └── resources/
│       └── application.properties     # Configuration
└── test/                              # Test files
\`\`\`

## Building for Production

\`\`\`bash
# Create executable JAR
mvn clean package

# Run the JAR
java -jar target/*.jar
\`\`\`

---

Generated by FormSync - Component 1: Intelligent Schema Definition & AI Integration
`;
  }

  /**
   * Generate .gitignore file
   */
  generateGitignore(): string {
    return `# Maven
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# IDE
.idea/
*.iml
.vscode/
.classpath
.project
.settings/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
`;
  }
}
